
###
GET http://localhost:3000/


### Profile info on logedin user
GET http://localhost:3000/profile


### View profile from frontend
GET http://localhost:5173/profile


###
GET http://localhost:3000/gyms


###
POST http://localhost:3000/gyms
Content-Type: application/json

{
    "name": "IronGym",
    "location": "Solna",
    "reviews": "Big and fansy"
}   


###
GET http://localhost:3000/gyms/3
